import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Sidebar from "@/components/shared/Sidebar";
import Rightbar from "@/components/shared/Rightbar/Rightbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body  className={inter.className}>
      <div className="px-16 pt-16 ">
<div className="bg-pink-50 rounded-t-2xl">
<Navbar/> 
    <div className="flex justify-between rounded-lg border">
    <Sidebar/> 

   

        {children}
        <Rightbar/>
        </div>
</div>

        </div>
        </body>
    </html>
  );
}
