import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Sidebar from "@/components/shared/Sidebar";
import Rightbar from "@/components/shared/Rightbar/Rightbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body  className={inter.className}>
        <div className="px-20 pt-16 ">
          <div className="bg-[#F9FAFE]  rounded-t-2xl">

             <div className="flex flex-1">
                <Sidebar/> 
            <div className=" w-full min-h-screen shadow-md rounded-t-2xl ">
                  <Navbar/> 
                  <div className="flex justify-between">
                   {children}
                    <Rightbar/>
                    </div>
                 </div>
           
           </div>
          </div>

        </div>
        </body>
    </html>
  );
}
